spring.application.name=api-blanck

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/webii_tp2
spring.datasource.username=webii_tp2
spring.datasource.password=webii_tp2
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html